# first nural network with tensorflow

<img src="Selection_001.png">

### we are going to make this nural network with tensorflow

In [1]:
## it does very simple linear fit to 2 dimentional array

### we build 
###                1) A graph
###                2) Initiate the SEssion
###                3) Feed data in and get output

In [2]:
import numpy as np
import tensorflow as tf

/home/pirate/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [3]:
## set up the  seed
np.random.seed(101)
tf.set_random_seed(101)

In [4]:
rand_a = np.random.uniform(1,100,(5,5))

In [5]:
print rand_a

[[52.12346414 57.4960911   3.81894842 17.98064397 68.84242119]
 [83.5557894  31.38965575 89.46769489 72.43284232 19.80395647]
 [55.86853152 35.86106345 19.00734786 78.77457442 96.58283902]
 [24.00301252  9.27258193 60.75129381 73.17028297 28.34764402]
 [68.84532655 52.26887995  5.79996921 14.64905452 19.50977519]]


In [6]:
rand_b = np.random.uniform(0,100,(5,1))

In [7]:
print rand_b

[[99.43179012]
 [52.06653967]
 [57.87895355]
 [73.48190583]
 [54.19617722]]


#### this is for array multiplication

In [8]:
## two data that means we need two place holders
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)

In [11]:
## now we create operationm
add_op = a+b
mul_op = a*b

In [16]:
with tf.Session() as sess:
        ## SO THIS ARE PLACEHOLDER SO WE MUST PROVIDE DATA
        add_result = sess.run(add_op,feed_dict={a:10,b:20})
        print (add_result)

30.0


In [17]:
with tf.Session() as sess:
        ## SO THIS ARE PLACEHOLDER SO WE MUST PROVIDE DATA
        add_result = sess.run(add_op,feed_dict={a:rand_a,b:rand_b})
        print (add_result)

[[151.55525  156.92789  103.25074  117.41244  168.27422 ]
 [135.62233   83.45619  141.53424  124.49939   71.8705  ]
 [113.74748   93.74002   76.8863   136.65353  154.46179 ]
 [ 97.48492   82.754486 134.2332   146.65219  101.829544]
 [123.041504 106.46506   59.996147  68.84523   73.705956]]


In [19]:
with tf.Session() as sess:
        ## SO THIS ARE PLACEHOLDER SO WE MUST PROVIDE DATA
        add_result = sess.run(add_op,feed_dict={a:rand_a,b:rand_b})
        print (add_result)
        print ("\n\n")
        mull_result = sess.run(mul_op,feed_dict={a:rand_a,b:rand_b})
        print (mull_result)

[[151.55525  156.92789  103.25074  117.41244  168.27422 ]
 [135.62233   83.45619  141.53424  124.49939   71.8705  ]
 [113.74748   93.74002   76.8863   136.65353  154.46179 ]
 [ 97.48492   82.754486 134.2332   146.65219  101.829544]
 [123.041504 106.46506   59.996147  68.84523   73.705956]]



[[5182.7295  5716.9395   379.72488 1787.8477  6845.1255 ]
 [4350.4604  1634.3508  4658.2734  3771.3276  1031.1235 ]
 [3233.612   2075.6008  1100.1254  4559.3896  5590.114  ]
 [1763.787    681.367   4464.1206  5376.6914  2083.0388 ]
 [3731.1538  2832.7734   314.33615  793.9228  1057.3552 ]]


In [20]:

#this is for next lesson
with tf.Session() as sess:
        ## SO THIS ARE PLACEHOLDER SO WE MUST PROVIDE DATA
        m=sess.run(tf.random_normal([2,3]))
        print (m)

[[ 0.3393362   0.47084194  0.0114582 ]
 [-0.23298067  1.0963182   1.1501856 ]]


In [21]:
#np.random.random([1,10])  ## that mes the first row of the whole feature
## an 1D array of 10 number

array([[0.91315356, 0.80792015, 0.40299783, 0.35722434, 0.95287671,
        0.34363158, 0.86509982, 0.83027771, 0.53816145, 0.92246937]])