# numpy basics

In [2]:
import numpy as np


In [4]:
my_list = [1,2,3]

In [6]:
arr=np.array(my_list)

In [9]:
type(arr)

numpy.ndarray

In [12]:
arr1=np.arange(0,10)

In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [20]:
np.zeros((3,2)) ## make two dimentional array of zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [21]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [32]:
##same thing
np.linspace(0,11,10)  ## it creates data of the same space between them

array([ 0.        ,  1.22222222,  2.44444444,  3.66666667,  4.88888889,
        6.11111111,  7.33333333,  8.55555556,  9.77777778, 11.        ])

In [40]:
np.random.randint(0,10)## random integer between the 1-9
## now if we want a 3x3 matrix of random number between0-9
#then
np.random.randint(0,10,(3,3))

array([[4, 0, 4],
       [3, 3, 7],
       [9, 8, 7]])

In [41]:
np.random.normal() ##random number from the normal distribution


-0.6297824039832868

In [42]:
##if you want to get a constant random number from the call
## then you have to seed it
np.random.seed(101)
np.random.randint(0,100,10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [43]:
np.random.seed(102)
np.random.randint(0,100,10)

array([ 0, 78, 66, 73, 72, 45, 72, 73, 79,  7])

In [44]:
## this are constant random number
np.random.seed(102)
ram=np.random.randint(0,100,10)


In [46]:
ram.max() ##give you the max

79

In [48]:
ram.min() ## give you the min

0

In [49]:
ram.mean() #avg

56.5

In [50]:
##find the index of the max value
ram.argmax()

8

In [51]:
########reshape
ram

array([ 0, 78, 66, 73, 72, 45, 72, 73, 79,  7])

In [52]:
ram.reshape(2,5) ## 2/5 matrix is possible to make with no absent of data with 10 value

array([[ 0, 78, 66, 73, 72],
       [45, 72, 73, 79,  7]])

In [54]:
try:
    ram.reshape(2,6) ## it is not possible
except:
    print('not possible')

not possible


In [55]:
matrix=np.arange(0,100)

In [56]:
matrix

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [57]:
## this is one dimensional array lets reshape the data with 10/10 matrix data is 100
matrix=matrix.reshape(10,10)

In [58]:
matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [60]:
#grabe single element
matrix[0][1]

1

In [62]:
matrix[3][3]

33

In [67]:
##lets say you want all the rows of the first column
matrix[:,0] ## all the row first value


array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [70]:
matrix[0:3,0:3]    ## first three column and first 3 value

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [72]:
## which value of the matrix is greater than 50
##apply boolian value
my_filter=matrix >50

In [73]:
matrix[my_filter]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [74]:
##its called bolian masking

In [75]:
## same thing we can do it with one command
matrix[matrix>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])