In [1]:
import numpy as np

In [2]:
## create a list of number
mylist=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]

In [3]:
## convert it to a numpy array
myarray=np.array(mylist)

In [4]:
print(myarray)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [5]:
myarray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [7]:
##make an array of zeros
myarray1=np.zeros(15)

In [8]:
len(myarray1)

15

#### np.arange(start,end,interval)

In [12]:
myarray2=np.arange(1,100,2)

In [13]:
print(myarray2)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [17]:
##make 4x4 matrix with zeros
myarray3=np.zeros((4,4))

In [18]:
myarray3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
##same thing with 1
myarray4=np.ones((5,5))

In [20]:
myarray4

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
#np.linspace(start,end,number_how_much_equally_divide)
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [23]:
np.linspace(1,11,10)

array([ 1.        ,  2.11111111,  3.22222222,  4.33333333,  5.44444444,
        6.55555556,  7.66666667,  8.77777778,  9.88888889, 11.        ])

In [24]:
## it divide the 1 to 11 with equal equal distence

In [34]:
mylist=np.arange(100)

In [35]:
mylist

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [37]:
## first reshape to 10x10
## find less than 30 and greater than 60

mynewlist=mylist.reshape(10,10)

In [40]:
mynewlist[mynewlist<30]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [41]:
mynewlist[mynewlist>60]

array([61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])