# tensor means array 

In [1]:
import tensorflow as tf

/home/pirate/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
print(tf.__version__)

1.13.1


In [3]:
## adding constant to the tensorflow
hello = tf.constant("hello") ## actually tensor are like array

In [4]:
world = tf.constant("World")  ## this is like array

In [17]:
print hello ## this result is not the hello

Tensor("Const:0", shape=(), dtype=string)


In [6]:
print(world)

Tensor("Const_1:0", shape=(), dtype=string)


In [7]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [8]:
sess = tf.Session()

In [9]:
sess.run(hello+" "+world)

'hello World'

In [10]:
a= tf.constant(10)

In [11]:
b=tf.constant(20)

In [12]:
a+b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [15]:
a+b

<tf.Tensor 'add_4:0' shape=() dtype=int32>

In [16]:
a+b

<tf.Tensor 'add_5:0' shape=() dtype=int32>

In [18]:
## tensorflow kepps traking this thing how many times you add thins thing

In [20]:
with tf.Session() as sess:
    result=sess.run(a+b)

In [21]:
result

30

In [22]:
const = tf.constant(100)

In [23]:
fill_mat = tf.fill((4,4),10)

In [34]:
myzeros = tf.zeros((4,4))

In [35]:
with tf.Session() as sess:
    result=sess.run(fill_mat)

In [36]:
result

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]], dtype=int32)

In [37]:
with tf.Session() as sess:
    result=sess.run(myzeros)

In [38]:
result

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)

In [39]:
myops = [const,fill_mat,myzeros]



In [40]:
sess = tf.InteractiveSession()

/home/pirate/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py:1702: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [41]:
for operation in myops:
    print(sess.run(operation))
    print("\n")

100


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


