In [1]:
import tensorflow as tf

/home/pirate/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [3]:
class TF1:
    def __init__(self,X,Y):
        self.hello = tf.constant(X)
        self.world = tf.constant(Y)
    def run(self):
        with tf.Session() as sess:
            print(sess.run(self.hello+self.world))

In [7]:
first = TF1('hello ','world')

In [8]:
first.run()

hello world


In [10]:
class TF2:
    def __init__(self,X,Y):
        self.a = tf.constant(X)
        self.b = tf.constant(Y)
        print(self.a+self.b)
        print(self.a+self.b)
        print(self.a+self.b)
                    
    def run(self):
        with tf.Session() as sess:
            print(sess.run(self.a+self.b))
    

In [12]:
second = TF2(10,20)

Tensor("add_2:0", shape=(), dtype=int32)
Tensor("add_3:0", shape=(), dtype=int32)
Tensor("add_4:0", shape=(), dtype=int32)


In [13]:
second.run()

30


In [20]:
class myops:
    def matrix_filling(self):
        return tf.fill((4,4),10)
    def zero_filling(self):
        return tf.zeros((4,4))
    def one_filling(self):
        return tf.ones((4,4))
    def run(self,x):
        with tf.Session() as sess:
            print(sess.run(x))
        

In [21]:
op=myops()

In [22]:
X=op.matrix_filling()

In [23]:
op.run(X)

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


In [26]:
Y=op.one_filling()
Z=op.zero_filling()

In [27]:
op.run(Y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [28]:
op.run(Y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [29]:
a=tf.constant([[1,2],[3,4]])

In [30]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [31]:
b=tf.constant([[10],[100]])

In [32]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [33]:
print(tf.matmul(a,b))

Tensor("MatMul:0", shape=(2, 1), dtype=int32)


In [35]:
with tf.Session() as sess:
    print(sess.run(tf.matmul(a,b)))

[[210]
 [430]]
